---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  serviceName: "zookeeper-cluster0"
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /data"]
        volumeMounts:
        - name: zookeeper-volume
          mountPath: /data
      containers:
      - name: zookeeper
        image: "k8s.gcr.io/kubernetes-zookeeper:1.0-3.4.10"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        command:
        - sh
        - -c
        - "start-zookeeper \
          --servers=3 \
          --data_dir=/var/lib/zookeeper/data \
          --data_log_dir=/var/lib/zookeeper/data/log \
          --conf_dir=/opt/zookeeper/conf \
          --client_port=2181 \
          --election_port=3888 \
          --server_port=2888 \
          --tick_time=2000 \
          --init_limit=10 \
          --sync_limit=5 \
          --heap=512M \
          --max_client_cnxns=60 \
          --snap_retain_count=3 \
          --purge_interval=12 \
          --max_session_timeout=40000 \
          --min_session_timeout=4000 \
          --log_level=INFO"
        volumeMounts:
        - name: zookeeper-volume
          mountPath: /data
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: zookeeper-volume
          hostPath:
            path: /data/zookeeper
            type: Directory
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Europe/Moscow
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-cluster0-server
  labels:
    app: zookeeper
    type: headless
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-cluster0-client
  labels:
    app: zookeeper
    type: headless
spec:
  clusterIP: None
  ports:
  - port: 2181
    name: client
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-external
  labels:
    app: zookeeper
    type: tcp
spec:
  type: NodePort
  ports:
  - nodePort: 31115
    port: 12181
    protocol: TCP
    targetPort: 2181
  selector:
    app: zookeeper
